[package]
name = "wdb-grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.11"
prost = "0.12"
tonic-reflection = "0.11.0"

[build-dependencies]
tonic-build = "0.11"
